name: update-node-hook
description: Action to automatically update node-based pre-commit hooks.
author: Paul Fischer <paul.fischer@mailbox.org>
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g npm@latest
      shell: bash
    - run: node ${{ github.action_path }}/dist/index.js
      shell: bash
